"""added status column to emergency requests

Revision ID: d94c9682289a
Revises: 6940b4075472
Create Date: 2025-10-27 23:09:43.638228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd94c9682289a'
down_revision = '6940b4075472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'resolved'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('active', 'resolved'),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))

    # ### end Alembic commands ###
