"""add file upload fields

Revision ID: e580b314841c
Revises: d94c9682289a
Create Date: 2026-03-13 00:38:09.479728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e580b314841c'
down_revision = 'd94c9682289a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('aadhaar_proof_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_source', sa.String(length=50), nullable=True))

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('aadhaar_proof_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_column('verification_source')
        batch_op.drop_column('aadhaar_proof_file')
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('verification_source')
        batch_op.drop_column('aadhaar_proof_file')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
